import { chromium } from "playwright";
const url = process.argv[2];
const outPath = process.argv[3];
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 375, height: 800 }, reducedMotion: "reduce" });
await page.goto(url, { waitUntil: "networkidle" });
await page.addStyleTag({ content: `.aa-reveal { opacity: 1 !important; transform: none !important; }` });
await page.waitForTimeout(300);
await page.screenshot({ path: outPath, fullPage: true });
await browser.close();
console.log("saved", outPath);
